In [ ]:
# NumPy Exercises
# How to create an empty and a full NumPy array?
# Create a Numpy array filled with all zeros
# Create a Numpy array filled with all ones
# Replace NumPy array elements that doesn’t satisfy the given condition
# Get the maximum value from given matrix

In [ ]:
#How to create an empty and a full NumPy array?

In [10]:
import numpy as np

empty_array = np.empty((3, 3))
print("Empty array:")
print(empty_array)

Empty array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
full_array = np.full((3, 3), 7)
print("Full array with 7s:")
print(full_array)

Full array with 7s:
[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
#Create a Numpy array filled with all zeros

In [12]:
zeros_array = np.zeros((3, 3))
print("Array filled with zeros:")
print(zeros_array)

Array filled with zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#Create a Numpy array filled with all ones

In [13]:
ones_array = np.ones((3, 3))
print("Array filled with ones:")
print(ones_array)

Array filled with ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#Replace NumPy array elements that doesn’t satisfy the given condition

In [14]:
array = np.array([156, 211, 323, 423, 523])
condition = array > 200
array[~condition] = 0
print("Array with elements not satisfying the condition replaced by 0:")
print(array)

Array with elements not satisfying the condition replaced by 0:
[  0 211 323 423 523]


In [ ]:
#Get the maximum value from given matrix

In [15]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
max_value = np.max(matrix)
print("Maximum value from the matrix:")
print(max_value)

Maximum value from the matrix:
9
