In [ ]:
# Python – Assigning Subsequent Rows to Matrix first row elements
# Adding and Subtracting Matrices in Python
# Python – Group similar elements into Matrix
# Python – Row-wise element Addition in Tuple Matrix
# Create an n x n square matrix, where all the sub-matrix have the sum of opposite corner elements as even

In [ ]:
#Assigning Subsequent Rows to Matrix first row elements

In [2]:
matrix=[[2,5,7],[8,4,5],[8,23,7]]
matrix[0]=matrix[1]
matrix

[[8, 4, 5], [8, 4, 5], [8, 23, 7]]

In [4]:
test_list = [[5, 8, 9], [2, 0, 9], [5, 4, 2], [2, 3, 9]]
print("The original list : " + str(test_list))
res = {test_list[0][ele] :  test_list[ele + 1] for ele in range(len(test_list) - 1)}
print("The Assigned Matrix : " + str(res))

The original list : [[5, 8, 9], [2, 0, 9], [5, 4, 2], [2, 3, 9]]
The Assigned Matrix : {5: [2, 0, 9], 8: [5, 4, 2], 9: [2, 3, 9]}


In [12]:
matrix1 = [[5, 8, 9], [2, 0, 9], [5, 4, 2], [2, 3, 9]]
print("matrix1 : " + str(matrix1))
matrix2 = {matrix1[0][ele] :  matrix1[ele + 1] for ele in range(len(matrix1) - 1)}
print("New Assigned Matrix : " + str(matrix2))

matrix1 : [[5, 8, 9], [2, 0, 9], [5, 4, 2], [2, 3, 9]]
New Assigned Matrix : {5: [2, 0, 9], 8: [5, 4, 2], 9: [2, 3, 9]}


In [ ]:
#Adding and Subtracting Matrices in Python

In [13]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[4,5],[6,7]])
print("first matrix",A)
print("second matrix",B)
add=np.add(A,B)
sub=np.subtract(A,B)
print("Add",add)
print("Sub",sub)

first matrix [[1 2]
 [3 4]]
second matrix [[4 5]
 [6 7]]
Add [[ 5  7]
 [ 9 11]]
Sub [[-3 -3]
 [-3 -3]]


In [ ]:
#Group similar elements into Matrix

In [11]:
from itertools import groupby
list1 = [1, 3, 5, 1, 3, 2, 5, 4, 2]
print("The original list : " + str(list1))
similar_ele= [list(val) for key, val in groupby(sorted(list1))]
print("Matrix after grouping : " + str(similar_ele))

The original list : [1, 3, 5, 1, 3, 2, 5, 4, 2]
Matrix after grouping : [[1, 1], [2, 2], [3, 3], [4], [5, 5]]


In [ ]:
#Row-wise element Addition in Tuple Matrix

In [12]:
matrix = (
    (7, 9, 3),
    (4, 6, 6),
    (7, 3, 9)
)
sum_row = tuple(sum(row) for row in matrix)

print("Row-wise sum:",sum_row)

Row-wise sum: (19, 16, 19)


In [ ]:
#Adding and Subtracting Matrices in Python

In [10]:
import numpy as np
a=[[2,4,6],[4,7,3],[8,4,6]]
b=[[8,4,3],[7,9,3],[9,7,5]]
c=a+b
add=np.add(a,b)
print("adding matrix",add)
sub=np.subtract(a,b)
print("subtracting matrix",sub)

adding matrix [[10  8  9]
 [11 16  6]
 [17 11 11]]
subtracting matrix [[-6  0  3]
 [-3 -2  0]
 [-1 -3  1]]


In [ ]:
#Create an n x n square matrix, where all the sub-matrix have the sum of opposite corner elements as even

In [11]:
def create_even_corner_sum_matrix(n):
    matrix=[[0]*n for _ in range(n)]
    for i in range(n):
        for j in range(n):
            matrix[i][j]=2*(i*n+j)
            return matrix
        
def print_matrix(matrix):
    for row in matrix:
        print(" ".join(map(str,row)))
        
n=4
matrix=create_even_corner_sum_matrix(n)
print_matrix(matrix)

0 0 0 0
0 0 0 0
0 0 0 0
0 0 0 0
